#!/bin/sh

if [ -f RUNNING_PID ];
then
  rm RUNNING_PID
fi

export JAVA_OPTIONS="-Xmx128M -XX:PermSize=64M -XX:MaxPermSize=128M"
echo "JAVA_OPTIONS=$JAVA_OPTIONS"
echo '(To change JAVA_OPTIONS, edit the "run" script!)'

cd ~/application
target/start -Dhttp.port=$PORT_WWW
